[prune]
go-tests = true
unused-packages = true

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.12"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.6.0"

[[constraint]]
  name = "k8s.io/kops"
  revision = "b48ed40551bf71a602754773d89c4bc5dbb3ef8d"
