[prune]
go-tests = true
unused-packages = true
  [[prune.project]]
  name = "github.com/golang/protobuf"
  unused-packages = false

# These should generally be synced with https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.18"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/protobuf"
  #revision = "925541529c1fa6821df4e44ce2723319eb2be768" # v1.0.0, as of 2018-02-16
  version = "v1.2.0"

[[constraint]]
  name = "golang.org/x/net"
  revision = "136a25c244d3019482a795d728110278d6ba09a4"  # master as of 2018-02-16

[[constraint]]
  name = "google.golang.org/grpc"
#  revision = "8e4536a86ab602859c20df5ebfd0bd4228d08655"  # v1.10.0, latest as of 2018-02-16
  version = "v1.12.1"

[[constraint]]
  name = "k8s.io/kops"
  revision = "24206f04f5eb8e1565b3e7edfbf40f84d5511e20" # shortly before 1.12.0

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.12.1"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "dcc6e84aef1b6713accea7d7d7252ad2bc0e7034"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.21.6"
