[prune]
go-tests = true
unused-packages = true

# These should generally be synced with https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.12"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "925541529c1fa6821df4e44ce2723319eb2be768" # v1.0.0, as of 2018-02-16

[[constraint]]
  name = "golang.org/x/net"
  revision = "136a25c244d3019482a795d728110278d6ba09a4"  # master as of 2018-02-16

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "8e4536a86ab602859c20df5ebfd0bd4228d08655"  # v1.10.0, latest as of 2018-02-16

[[constraint]]
  name = "k8s.io/kops"
  revision = "cccd71e67e681754759c5cf7f66850d8908613b6" # 1.9.0

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.10.1"
