# See https://cloud.google.com/cloud-build/docs/build-config
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
- name: gcr.io/k8s-testimages/krte:latest-master
  env:
  - PULL_BASE_REF=$_PULL_BASE_REF
  - VERSION=$_GIT_TAG
  - DOCKER_REGISTRY=$_DOCKER_REGISTRY
  - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
  - ARTIFACT_LOCATION=$_ARTIFACT_LOCATION
  - INSTALL_BAZEL_VERSION=3.4.1
  entrypoint: dev/staging/push.sh
substitutions:
  _GIT_TAG: 'dev'
  _PULL_BASE_REF: 'dev'
  _DOCKER_REGISTRY: 'gcr.io'
  _DOCKER_IMAGE_PREFIX: 'k8s-staging-etcdadm/'
  _ARTIFACT_LOCATION: 'gs://k8s-staging-etcdadm/ci/builds/'
